### ISSUE TITLE
t265.stl missing, Failed to load nodelet '/livox_right_filter'

### ISSUE THREAD

**Issue by JACKLiuDay** [qiayuanl/legged_perceptive#6]
Hi, thank you for your great work about legged_perceptive. I have some errors when launch load_controller.launch
![image](https://github.com/qiayuanl/legged_perceptive/assets/30967867/eeaec9f0-09f6-41c6-a105-303535bd6c43)

**Comment by nfhe** [comment]
Have you solved this problem? I meet the same problem. If you can help, I would appreciate it!!!

**Comment by JACKLiuDay** [comment]
> Have you solved this problem? I meet the same problem. If you can help, I would appreciate it!!!

Sorry, I just changed the lidar plugin. You can find some other lidar plugins on github. It looks like the sensor filter can not work.
